### ISSUE TITLE
"Create problem" page doesn't validate user's input

### ISSUE THREAD

**Issue by naturetime10** [CoverCoding/frontend#3]
http://cover.wehackers.club/new/problem

Title: Any String
School: Default to be WPI, currently not changeable
Course Number: Two Characters append with 3 or 4 numbers
Term: A, B, C, D, E1, E2
Year: 4 digits number
Instructor: Any String
Problem body: Any String

**Comment by binamkayastha** [comment]
@byliuyang 
Please verify that the code I would be changing would be from these two files:
 - src/app/topbar-pages/new/new-problem/new-problem-form/new-problem-form.component.ts (Where verification logic should go)
 - src/app/topbar-pages/new/new-problem/new-problem-form/new-problem-form.component.spec.ts (Where tests should go)

**Comment by naturetime10** [comment]
@binamkayastha Here you go!
